name: Auto Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      # -------- DEV --------
      - run: git checkout dev
      - run: git merge main --no-edit
      - run: echo "${{ secrets.VITE_DEV_ENV }}" > .env
      - run: npm run build
      - run: |
          git config user.name "ci-bot"
          git config user.email "ci@github.com"
          git add public/build
          git commit -m "build dev" || echo "no changes"
          git push origin dev

      # -------- PROD --------
      - run: git checkout deploy
      - run: git merge main --no-edit
      - run: echo "${{ secrets.VITE_PROD_ENV }}" > .env
      - run: npm run build
      - run: |
          git add public/build
          git commit -m "build prod" || echo "no changes"
          git push origin deploy
